### ISSUE TITLE
enable local data server

### ISSUE THREAD

**Issue by manzt** [gosling-lang/grosling#1]
Gos enables local files and pandas dataframes to be visualized with Gosling. For some reason the background dataserver in the R environment times out. This is an essential feature and otherwise R users cannot easily view their own local datasets.

**Comment by elliothershberg** [comment]
If useful, the JBrowseR package has [`serve_data()`](https://gmod.github.io/JBrowseR/reference/serve_data.html) which you could point people to or write a small wrapper for. It's based on the [servr](https://github.com/yihui/servr) package, but I adapted it to implement support for range requests.

**Comment by manzt** [comment]
Thanks for the suggestion, @elliothershberg! I dug into this further yesterday, and my best understanding of the issue is something internal to `reticulate` which are causing issues with `threads` in Python. It appears others might have a similar issue:

- https://github.com/rstudio/reticulate/issues/515

I might need to try out [`basilisk`](https://bioconductor.org/packages/release/bioc/html/basilisk.html) for this reason alone. However, in the meantime having _some_ way of supporting local files is necessary. I'll work on adding a section to the readme that points to `serve_data()` (the range request support is certainly a requirement as you noted). The only outstanding issue then is that some of the data sources for Gosling are based on HiGlass server (not static files) and we still won't have a work around for that.
